#!/bin/sh
#
# The hook should exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Redirect output to stderr.
poetry run python AoCTiles/create_aoc_tiles.py 1>&2
