name: Advent of Code

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: mortenlj/mise-lib/.github/workflows/setup.yaml@main

  ci:
    needs: setup
    uses: mortenlj/mise-lib/.github/workflows/ci.yaml@main
    with:
      ci-tasks: ${{ needs.setup.outputs.ci-tasks }}
